refactor: updating the project
Snowfork/snowbridge-app pull request #16
Opened 2024-08-06 14:27 UTC by Dudleyneedham

# Refactor the transaction

Updating the current project to split the different functions and reduce the noise in the `transaction.ts` file.

Moving things to the utils that could be used again.

If the types will be exported, move it to its file in the `utils` dir.

Renaming components to align with React convention.

2024-08-06 14:28 UTC, Dudleyneedham commented
I will continue to work on the app refactor. Additionally, I will update the eslint and styles to match the current apps implementation instead of changing it.

2024-08-07 13:46 UTC, Dudleyneedham commented
I have updated the eslint and added prettier as I noticed some places had trailing semi-colons, and others did not. Additionally, I wanted to make it easier for others who use the project without relying on their settings in the editor and mixing and matching with the project owners. I tried my best to match Alister's current settings. 

I sorted more utility functions into separate files and merged some similar files into a more uniform file, e.g. formatting, and will move the `utils/balances` into a singular file.

2024-08-07 20:01 UTC, alistair-singh requested changes
Looks good. Minor comments.

2024-08-07 20:22 UTC, alistair-singh commented
Preview builds failed. Seems related to the case of files. Need to commit and push the rename explicitly with git.
```
[22:19:46.572]   ▲ Next.js 14.2.3
[22:19:46.572] 
[22:19:46.650]    Creating an optimized production build ...
[22:20:16.568] Failed to compile.
[22:20:16.569] 
[22:20:16.569] ./app/history/page.tsx
[22:20:16.569] Module not found: Can't resolve '@/components/ErrorDialog'
[22:20:16.570] 
[22:20:16.570] https://nextjs.org/docs/messages/module-not-found
[22:20:16.570] 
[22:20:16.570] ./app/status/page.tsx
[22:20:16.570] Module not found: Can't resolve '@/components/ErrorDialog'
[22:20:16.570] 
[22:20:16.570] https://nextjs.org/docs/messages/module-not-found
[22:20:16.570] 
[22:20:16.570] ./app/layout.tsx
[22:20:16.570] Module not found: Can't resolve '@/components/BridgeStatus'
[22:20:16.570] 
[22:20:16.570] https://nextjs.org/docs/messages/module-not-found
[22:20:16.570] 
[22:20:16.570] ./app/layout.tsx
[22:20:16.570] Module not found: Can't resolve '@/components/Footer'
[22:20:16.570] 
[22:20:16.570] https://nextjs.org/docs/messages/module-not-found
[22:20:16.570] 
[22:20:16.570] ./app/layout.tsx
[22:20:16.570] Module not found: Can't resolve '@/components/Menu'
[22:20:16.570] 
[22:20:16.570] https://nextjs.org/docs/messages/module-not-found
[22:20:16.570] 
[22:20:16.579] 
[22:20:16.579] > Build failed because of webpack errors
[22:20:16.588]  ELIFECYCLE  Command failed with exit code 1.
[22:20:16.610] Error: Command "pnpm run build" exited with 1
[22:20:17.042] 
```

2024-08-08 08:06 UTC, Dudleyneedham commented on components/ui/accordion.tsx
> +import { cn } from "@/utils/cn";
Ok, I haven't used shadon before, but I will move it back. I thought someone had made it.

2024-08-08 08:06 UTC, Dudleyneedham commented on components/ui/avatar.tsx
> +"use client";
I will revert the changes. I was wondering why the formatting was different only in the UI components.

2024-08-08 08:44 UTC, Dudleyneedham commented on eslint.config.js
> +    ignores: [".next/**/*"],
I added it in both prettier and eslint

2024-08-30 01:10 UTC, alistair-singh approved these changes

2024-08-30 01:10 UTC, merged